/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package consumer;

import com.rabbitmq.client.Connection;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
}
