/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package upicclient;

import org.junit.Test;
import upicclientpart1.UpicClientPart1;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        UpicClientPart1 classUnderTest = new UpicClientPart1();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
